---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
  data:
    aws-access-key-id: ''
    aws-secret-access-key: ''
    azure-storage-account: ''
    azure-storage-connection-string: ''
    insights-url: ''
    insights-user: ''
    insights-password: ''
    insights-account: ''
    insights-org-id: ''
    gcp-dataset: ''
    gcp-project-id: ''
  type: Opaque

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ${NAME}
  spec:
    envName: ${ENV_NAME}
    jobs:
    - name: ${NAME}
      schedule: ${POPULATE_SCHEDULE}
      restartPolicy: Never
      concurrencyPolicy: Forbid
      startingDeadlineSeconds: ${{POPULATE_STARTING_DEADLINE}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["python", "nise-populator/app.py"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws-access-key-id
                name: ${SECRET_NAME}
                optional: true
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws-secret-access-key
                name: ${SECRET_NAME}
                optional: true
          - name: AZURE_STORAGE_ACCOUNT
            valueFrom:
              secretKeyRef:
                key: azure-storage-account
                name: ${SECRET_NAME}
                optional: true
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                key: azure-storage-connection-string
                name: ${SECRET_NAME}
                optional: true
          - name: INSIGHTS_URL
            valueFrom:
              secretKeyRef:
                key: insights-url
                name: ${SECRET_NAME}
                optional: true
          - name: INSIGHTS_USER
            valueFrom:
              secretKeyRef:
                key: insights-user
                name: ${SECRET_NAME}
                optional: true
          - name: INSIGHTS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: insights-password
                name: ${SECRET_NAME}
                optional: true
          - name: HCC_SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                key: hcc-service-account-id
                name: ${SECRET_NAME}
                optional: true
          - name: HCC_SERVICE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                key: hcc-service-account-secret
                name: ${SECRET_NAME}
                optional: true
          - name: HCC_TOKEN_URL
            valueFrom:
              secretKeyRef:
                key: hcc-token-url
                name: ${SECRET_NAME}
                optional: true
          - name: INSIGHTS_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                key: insights-account
                name: ${SECRET_NAME}
                optional: true
          - name: INSIGHTS_ORG_ID
            valueFrom:
              secretKeyRef:
                key: insights-org-id
                name: ${SECRET_NAME}
                optional: true
          - name: GCP_DATASET
            valueFrom:
              secretKeyRef:
                key: gcp-dataset
                name: ${SECRET_NAME}
                optional: true
          - name: GCP_PROJECT_ID
            valueFrom:
              secretKeyRef:
                key: gcp-project-id
                name: ${SECRET_NAME}
                optional: true
          - description: GCP Credentials Location
            name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcp/gcp-credentials-qe.json
          - name: POPULATE_SOURCES
            value: ${POPULATE_SOURCES}
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumeMounts:
        - mountPath: /etc/gcp
          name: gcp-credentials-qe
          readOnly: true
        volumes:
        - name: gcp-credentials-qe
          secret:
            items:
            - key: gcp-credentials-qe
              path: gcp-credentials-qe.json
            secretName: koku-gcp



parameters:
- description: The name
  name: NAME
  value: nise-populator
- description: Initial amount of CPU
  name: CPU_REQUEST
  value: 100m
- description: Initial amount of memory
  name: MEMORY_REQUEST
  value: 256Mi
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 300m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/redhat-services-prod/cost-mgmt-dev-tenant/nise-populator
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  requred: false
- name: POPULATE_SCHEDULE
  value: '0 15 * * *'
- name: POPULATE_STARTING_DEADLINE
  value: '300'
- name: POPULATE_SOURCES
  value: 'AWS,Azure,OCP,GCP'
- name: SECRET_NAME
  value: nise-populator-secret
