apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/project-koku/nise-populator?rev={{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: nise-populator
    appstudio.openshift.io/component: nise-populator
    pipelines.appstudio.openshift.io/type: build

  namespace: cost-mgmt-dev-tenant
  name: nise-populator-push

spec:
  params:
    - name: git-url
      value: '{{source_url}}'

    - name: revision
      value: '{{revision}}'

    - name: output-image
      value: quay.io/redhat-user-workloads/cost-mgmt-dev-tenant/nise-populator:{{ revision }}

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

  pipelineRef:
    name: pipeline-build

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'

  finally:
    - name: notify-success
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Succeeded"]
      params:
        - name: message
          value: |
            :white_check_mark: Pipeline `<$(context.pipelineRun.name)>` has completed successfully.
            See details: <https://console.redhat.com/application-pipeline/workspaces/cost-mgmt-dev/applications/nise-populator/pipelineruns/$(context.pipelineRun.name)|Pipeline Run>.
        - name: secret-name
          value: "slack-webhook-notification-secret"
        - name: key-name
          value: "webhook-url"
      taskRef:
        name: slack-webhook-notification
        bundle: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:dc17b70633363d78414b8c06dc1660d25742935f106a6116995638e1210c2730
    - name: notify-failure
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed", "Completed"]
      params:
        - name: message
          value: |
            :x: Pipeline `<$(context.pipelineRun.name)>` has failed or completed with issues.
            See details: <https://console.redhat.com/application-pipeline/workspaces/cost-mgmt-dev/applications/nise-populator/pipelineruns/$(context.pipelineRun.name)|Pipeline Run>.
        - name: secret-name
          value: "slack-webhook-notification-secret"
        - name: key-name
          value: "webhook-url"
      taskRef:
        name: slack-webhook-notification
        bundle: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:dc17b70633363d78414b8c06dc1660d25742935f106a6116995638e1210c2730
